# Generated by Django 4.1.7 on 2023-02-19 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('song', models.CharField(max_length=250)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
